apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc  # Name of the StorageClass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2  # Change to gp3 if you want to use the newer generation
  fsType: ext4  # File system type
reclaimPolicy: Delete  # Specify whether the volume should be deleted on PVC deletion
volumeBindingMode: WaitForFirstConsumer  # Ensure volume is created in the same availability zone as the pod

