apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: ci
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp2  # Ensure this matches your StorageClass

