apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ci
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data"
          name: jenkins
  volumes:
    - name: jenkins
      persistentVolumeClaim:
        claimName: jenkins

